// react-gs/src/App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';

import { Button } from 'devextreme-react/button';
import notify from 'devextreme/ui/notify';

function onClick() {
  notify("The button was clicked");
}

function App() {
  return (
    <div className="App">
      <div id="app-container">
      <Button
        text="Show the message"
        type="success"
        stylingMode="outlined"
        width={200}
        height={40}
        icon="comment"
        hint="Click to show the message"
        onClick={onClick}
      />

      </div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import notify from 'devextreme/ui/notify';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  click = () => {
    notify("The button was clicked");
  }
}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Angular: Getting started with Button</title>
</head>
<body class="dx-viewport"> 
  <dx-button
    text="Show the message"
    type="success"
    stylingMode="outlined"
    [width]="200"
    [height]="40"
    icon="comment"
    hint="Click to show the message"
    (onClick)="click()">
  </dx-button>
</body>
</html>
